// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVvRblxjgqpTKQhmb3wWWoZNc84ZW68Ys',
    appId: '1:789472975334:web:550bcb4240422b299b9e27',
    messagingSenderId: '789472975334',
    projectId: 'pure-health-clinic',
    authDomain: 'pure-health-clinic.firebaseapp.com',
    storageBucket: 'pure-health-clinic.appspot.com',
    measurementId: 'G-J75NZH35LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd6RuwbPhtHm9O8Ec0z4satls8VbRwKes',
    appId: '1:789472975334:android:079b530b0cd46f3c9b9e27',
    messagingSenderId: '789472975334',
    projectId: 'pure-health-clinic',
    storageBucket: 'pure-health-clinic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXXK0DSmcv6CohrPUdGpy648qROtvNhrU',
    appId: '1:789472975334:ios:9adfc10e9c6341399b9e27',
    messagingSenderId: '789472975334',
    projectId: 'pure-health-clinic',
    storageBucket: 'pure-health-clinic.appspot.com',
    iosBundleId: 'com.example.pureHealthClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXXK0DSmcv6CohrPUdGpy648qROtvNhrU',
    appId: '1:789472975334:ios:9adfc10e9c6341399b9e27',
    messagingSenderId: '789472975334',
    projectId: 'pure-health-clinic',
    storageBucket: 'pure-health-clinic.appspot.com',
    iosBundleId: 'com.example.pureHealthClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVvRblxjgqpTKQhmb3wWWoZNc84ZW68Ys',
    appId: '1:789472975334:web:fdd183da3368d3279b9e27',
    messagingSenderId: '789472975334',
    projectId: 'pure-health-clinic',
    authDomain: 'pure-health-clinic.firebaseapp.com',
    storageBucket: 'pure-health-clinic.appspot.com',
    measurementId: 'G-FL9WEV683F',
  );
}
